[package]
name = "jawa"
edition = "2024"
license = "MIT OR Apache-2.0"
version = "0.1.0"

[dependencies]
cxx = "1.0"
cxx-qt = "0.8"
cxx-qt-lib = { version = "0.8", features = ["qt_full"] }
cxx-qt-lib-extras = "0.8"

[build-dependencies]
cxx-qt-build = "0.8"

