[package]
name = "notifications"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
cxx.workspace = true
cxx-qt.workspace = true
cxx-qt-lib.workspace = true
cxx-qt-widgets.workspace = true

[build-dependencies]
cxx-qt-build.workspace = true